[package]
name = "h3ron"
description = "High-level rust API for H3"
version = "0.13.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"
license = "MIT"
keywords = ["geo", "spatial", "h3"]
readme = "../README.md"
homepage = "https://github.com/nmandery/h3ron"
repository = "https://github.com/nmandery/h3ron"

[features]
use-rayon = ["rayon", "num_cpus"]
io = ["bincode", "lz4_flex", "serde"]
use-serde = ["serde", "bincode"]
use-roaring = ["roaring"]

[dependencies]
geo = "^0.18"
itertools = "^0.10"
thiserror = "1.0"
svgbobdoc = "^0.2"
ahash = "0.7"

[dependencies.h3ron-h3-sys]
path = "../h3ron-h3-sys"
version = "0.12.0" # for publishing on crates.io

[dependencies.geo-types]
version = "^0.7"

[dependencies.serde]
version = "^1.0"
features = [ "derive" ]
optional = true

[dependencies.hashbrown]
version = "0.11"
features = ["rayon", "serde"]

[dependencies.rayon]
version = "1.5"
optional = true

[dependencies.num_cpus]
version = "1"
optional = true

[dependencies.bincode]
version = "1"
optional = true

[dependencies.roaring]
version = "0.8"
optional = true

[dependencies.lz4_flex]
version = "0.9"
default_features = false # disables the `safe-*code` features and uses a faster but unsafe algorithm
features = ["frame"]
optional = true

[dev-dependencies]
bincode = "1"

[dev-dependencies.geojson]
version = "^0.22"
features = [
    "geo-types"
]

[dev-dependencies.criterion]
version = "^0.3"
features = ["html_reports"]

[[bench]]
name = "k_ring_variants"
harness = false
